# Generated by Django 3.1.7 on 2021-03-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('size', models.CharField(max_length=90)),
                ('amount', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('Landmark', models.CharField(max_length=111)),
                ('house_no', models.CharField(max_length=111)),
                ('district', models.CharField(max_length=111)),
                ('pin_code', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(default='Free', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=60),
        ),
    ]
