# Generated by Django 3.1.7 on 2021-03-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210325_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='returnable',
            field=models.CharField(default='YES', max_length=20),
        ),
    ]
