# Generated by Django 3.1.7 on 2021-03-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_house_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateOrder',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestap', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
